# Generated by Django 3.0.1 on 2022-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_banner_bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Home Banner Bottom',
            },
        ),
        migrations.AlterModelOptions(
            name='home_banners_top',
            options={'verbose_name_plural': 'Home Banners Top'},
        ),
    ]
