# Generated by Django 3.0.1 on 2022-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20220828_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Vertical Banner',
            },
        ),
    ]
