# Generated by Django 3.0.1 on 2022-08-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_verticalbanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_banner_bottom',
            new_name='BannerBottom',
        ),
    ]
