# Generated by Django 3.0.1 on 2022-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20220828_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_banners_top',
            new_name='BannerCarousel',
        ),
    ]
