# Generated by Django 3.0.1 on 2022-08-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20220828_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerticalBanner',
            new_name='BannerVerical',
        ),
    ]
