# Generated by Django 3.0.1 on 2022-08-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20220828_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercarousel',
            options={'verbose_name_plural': 'Home Banners Carousel'},
        ),
    ]
