# Generated by Django 3.0.1 on 2022-09-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_auto_20220828_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerVerical',
            new_name='BannerVertical',
        ),
    ]
