# Generated by Django 3.0.1 on 2022-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220826_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_author',
            field=models.CharField(max_length=20),
        ),
    ]
