# Generated by Django 3.0.1 on 2022-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220826_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review_author',
            new_name='name',
        ),
    ]
