# Generated by Django 3.0.1 on 2022-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220827_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='service_review',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
