# Generated by Django 3.0.1 on 2022-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0013_auto_20220921_1035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="service_review",
            field=models.TextField(max_length=400, null=True),
        ),
    ]
