# Generated by Django 3.0.1 on 2022-08-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_new_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_product',
            new_name='comming_soon',
        ),
    ]
