# Generated by Django 3.0.1 on 2022-09-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220828_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender_category',
            new_name='GenderCategory',
        ),
    ]
