# Generated by Django 3.0.1 on 2022-09-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_auto_20220902_1052"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="promotion",
            new_name="sales",
        ),
    ]
