# Generated by Django 3.0.1 on 2022-09-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220911_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coming_soon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
    ]
