# Generated by Django 3.0.1 on 2022-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_auto_20220912_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="coming_soon",
            field=models.BooleanField(default=False),
        ),
    ]
